		-- Netflix--
            
CREATE DATABASE IF NOT EXISTS db_netflix
COLLATE utf8mb4_general_ci 
charset utf8mb4;
use db_netflix;

CREATE TABLE IF NOT EXISTS tb_Pais (
id_pais INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100),
codigo CHAR(2) NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Plano (
id_plano INT PRIMARY KEY AUTO_INCREMENT,
valor INTEGER NOT NULL,
descricao VARCHAR(100)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Pagamento (
id_pagamento INT PRIMARY KEY AUTO_INCREMENT,
forma_pagamento VARCHAR(100)NOT NULL,
valor INTEGER NOT NULL,
dt_pagamento DATE NOT NULL,
id_cartao INTEGER NOT NULL,
id_cliente INTEGER NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Tipo_pagamento (
id_pagamento INT PRIMARY KEY,
nome VARCHAR(100) UNIQUE NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Cartao_credito (
id_cartao INT PRIMARY KEY AUTO_INCREMENT,
numero VARCHAR(255) NOT NULL,
dt_vencimento DATE NOT NULL,
cod_seguranca INTEGER NOT NULL,
titular VARCHAR(100)NOT NULL,
nome CHAR(20) UNIQUE NOT NULL)
AUTO_INCREMENT = 1;

drop table tb_cartao_credito;

CREATE TABLE IF NOT EXISTS tb_Classificacao (
id_classificacao INT PRIMARY KEY AUTO_INCREMENT,
idade DATE NOT NULL,
descricao VARCHAR(10)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Categoria (
id_categoria INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_catalogo_idioma (
id_catalogo INT NOT NULL,
id_idioma INT NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Ator (
id_ator INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(255)NOT NULL,
sobrenome VARCHAR(100)NOT NULL,
dt_nascimento DATE NOT NULL,
foto VARCHAR(255)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Endereco (
id_pais INT PRIMARY KEY AUTO_INCREMENT,
id_usuario INT NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Usuario (
id_usuario INT PRIMARY KEY AUTO_INCREMENT,
senha VARCHAR(100) NOT NULL,
data DATE NOT NULL,
nome VARCHAR(100)NOT NULL,
sobrenome VARCHAR(100)NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
dt_cadastro DATE NOT NULL,
dt_nascimento DATE NOT NULL,
status VARCHAR(100)NOT NULL,
id_cliente INTEGER NOT NULL,
id_funcionario INTEGER NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_funcionario (
id_funcionario INT PRIMARY KEY AUTO_INCREMENT,
nivel_acesso INTEGER NOT NULL,
foto VARCHAR(255)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_cliente (
id_cliente INT PRIMARY KEY AUTO_INCREMENT,
id_perfil INT NOT NULL,
id_cartao INT NOT NULL,
dt_venc_plano DATE NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_idioma (
id_idioma INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_filme (
id_filme INT PRIMARY KEY AUTO_INCREMENT,
oscar VARCHAR(100)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_episodio (
id_episodio INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100)NOT NULL,
duracao TIME NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_serie (
id_serie INT PRIMARY KEY AUTO_INCREMENT,
qtd_episodios INTEGER NOT NULL)
AUTO_INCREMENT = 1;



CREATE TABLE IF NOT EXISTS tb_catalogo (
    id_catalogo INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    imagem_capa BIT,
    idioma_original VARCHAR(100) NOT NULL,
    duracao TIME NOT NULL,
    ano_lancamento DATE NOT NULL,
    pais_origem VARCHAR(100) NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    avaliacao INT NOT NULL,
    idioma_disponivel VARCHAR(100) NOT NULL,
    sinopse VARCHAR(255) NOT NULL,
    qtd_episodio INT NOT NULL,
    oscar VARCHAR(100) NOT NULL,
    id_classificacao INTEGER NOT NULL,
    id_idioma INT NOT NULL,
    id_filme INT NOT NULL,
    id_episodio INT NOT NULL,
    id_serie INT NOT NULL,
    id_ator INT NOT NULL,
    CONSTRAINT fk_id_classificacao FOREIGN KEY (id_classificacao) REFERENCES tb_classificacao(id_classificacao),
    CONSTRAINT fk_id_idioma FOREIGN KEY (id_idioma) REFERENCES tb_idioma (id_idioma),
    CONSTRAINT fk_id_id_filme FOREIGN KEY (id_filme) REFERENCES tb_filme (id_filme),
    CONSTRAINT fk_id_episodio FOREIGN KEY (id_episodio) REFERENCES tb_episodio (id_episodio),
    CONSTRAINT fk_id_serie FOREIGN KEY (id_serie) REFERENCES tb_serie (id_serie),
    CONSTRAINT fk_id_ator FOREIGN KEY (id_ator) REFERENCES tb_ator (id_ator)
) AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_pais_catalogo (
id_catalogo INTEGER PRIMARY KEY AUTO_INCREMENT,
id_pais INT NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_catalogo_categoria (
id_catalogo INTEGER NOT NULL,
id_categoria INTEGER NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_Temporada (
id_temporada INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(100)NOT NULL,
descricao VARCHAR(100)NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_serie_temporada (
id_temporada INT NOT NULL,
id_serie INT NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_temporada_episodio (
id_temporada INTEGER NOT NULL,
id_episodio INTEGER NOT NULL,
quant_episodio INTEGER NOT NULL)
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS tb_contrata (
id_vencimento INT PRIMARY KEY AUTO_INCREMENT,
id_cliente INTEGER NOT NULL,
id_plano INTEGER NOT NULL)
AUTO_INCREMENT = 1;

